name: "Ansible CLI Github Action"
description: "Allows one to run Ansible and Linux related commands"
inputs:
  command:
    description: "Ansible command to execute (e.g., 'ansible-playbook site.yml', 'ansible-galaxy install -r requirements.yml')"
    required: true
    default: "ansible-playbook"
branding:
  icon: 'terminal'
  color: 'red'
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
