name: Run 

on:
  workflow_dispatch: 
    inputs:
      command:
        description: "Command to execute"
        required: true
        default: "ansible-playbook"

jobs: 
  run: 
    runs-on: ubuntu-latest
    steps: 
      - uses: eftechcombr/ansible-cli-github-action@master
        with:
          command: "ansible --version"
    
