name: Docker

on:
  workflow_dispatch: 

jobs: 
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      uses: actions/ansible-cli-action@latest
      with:
        command: "ansible-playbook main.yml